server:
  port: 8079
spring:
  cloud:
    config:
      server:
        git:
          default-label: circuit-breaker
          uri: https://github.com/FranciscoJesusMC/microservicios
          search-paths: config-data
  application:
    name: config-service          